Repository choi2h/daily-nuts, pull requests merged in 2025-07, with the labels that each got.

#7 refactor: 게시글 API 테스트 가능하도록 리팩토링
  daily-nuts-server/src/main/java/com/dailynuts/post/repository/CategoryRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/post/service/PostServiceImpl.java
Labels: fix

#6 Feat/comment
  daily-nuts-server/src/main/java/com/dailynuts/post/controller/CommentController.java
  daily-nuts-server/src/main/java/com/dailynuts/post/dto/CommentListResponse.java
  daily-nuts-server/src/main/java/com/dailynuts/post/dto/CommentRequest.java
  daily-nuts-server/src/main/java/com/dailynuts/post/dto/CommentResponse.java
  daily-nuts-server/src/main/java/com/dailynuts/post/entity/Comment.java
  daily-nuts-server/src/main/java/com/dailynuts/post/repository/CommentRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/post/service/CommentService.java
  daily-nuts-server/src/main/java/com/dailynuts/post/service/CommentServiceImpl.java
  daily-nuts-server/src/main/java/com/dailynuts/post/service/mapper/CommentMapper.java
Labels: feature

#10 feat: 전체적인 화면 추가 및 수정
  daily-nuts-client/src/App.jsx
  daily-nuts-client/src/assets/css/mypage.css
  daily-nuts-client/src/assets/css/navigationbar.css
  daily-nuts-client/src/assets/css/post-write.css
  daily-nuts-client/src/assets/css/profile.css
  daily-nuts-client/src/assets/css/subscription-modal.css
  daily-nuts-client/src/components/BasicHeader.jsx
  daily-nuts-client/src/components/MyPageCard.jsx
  daily-nuts-client/src/components/PaymentHistory.jsx
  daily-nuts-client/src/components/PostDetailItem.jsx
  daily-nuts-client/src/components/PostForm.jsx
  daily-nuts-client/src/components/PostItem.jsx
  daily-nuts-client/src/components/Sidebar.jsx
  daily-nuts-client/src/components/SubTab.jsx
  daily-nuts-client/src/components/SubscriptionModal.jsx
  daily-nuts-client/src/layers/BlankHeaderLayout.jsx
  daily-nuts-client/src/layers/TabHeaderLayout.jsx
  daily-nuts-client/src/pages/MyPage.jsx
  daily-nuts-client/src/pages/PostDetailPage.jsx
  daily-nuts-client/src/pages/PostWritePage.jsx
  daily-nuts-client/src/pages/ProfilePage.jsx
Labels: design

#9 feat: 결제준비, 결제응답, 결제 내역 조회 기능 개발
  daily-nuts-server/src/main/java/com/dailynuts/common/exception/CustomErrorCode.java
  daily-nuts-server/src/main/java/com/dailynuts/member/repository/MemberRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/controller/PaymentController.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/controller/ProductController.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/PaymentPrepareInfoDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/PaymentRequestDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/PaymentResponseDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/ProductRequestDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/ProductResponseDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/ProductsResponseDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/entity/Payment.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/entity/Subscription.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/repository/PaymentRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/repository/SubscriptionRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/PaymentService.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/PaymentServiceImpl.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/ProductService.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/ProductServiceImpl.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/mapper/PaymentMapper.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/mapper/ProductMapper.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/portone/PortOneClient.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/portone/PortOnePaymentInfo.java
Labels: feature

#13 Feat: 알림 SSE 연동 개발
  daily-nuts-client/src/App.jsx
  daily-nuts-client/src/components/Sidebar.jsx
  daily-nuts-client/src/pages/NotificationPage.jsx
  daily-nuts-client/src/service/NotificationService.jsx
  daily-nuts-server/src/main/java/com/dailynuts/notification/controller/NotificationConnectController.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/controller/NotificationInfoController.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/dto/NotificationDto.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/dto/NotificationResponseDto.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/dto/SendMessageRequest.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/entity/Notification.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/entity/NotificationType.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/repository/NotificationRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/service/NotificationConnectService.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/service/NotificationInfoService.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/service/mapper/NotificationMapper.java
  daily-nuts-server/src/main/java/com/dailynuts/notification/service/message/MessageFormatter.java
  daily-nuts-server/src/main/java/com/dailynuts/post/service/PostLikeServiceImpl.java
Labels: feature

#15 Feat/payment 결제 준비, 결제 확인, 결제 내역 조회 기능 프론트 연동
  daily-nuts-client/index.html
  daily-nuts-client/src/components/PaymentHistory.jsx
  daily-nuts-client/src/components/SubscriptionModal.jsx
  daily-nuts-server/src/main/java/com/dailynuts/common/exception/CustomErrorCode.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/PaymentRequestDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/PortOneTokenRequestDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/repository/SubscriptionRepository.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/PaymentServiceImpl.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/portone/PortOneClient.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/portone/PortOnePaymentInfo.java
Labels: feature

#18 feat: 전반적인 화면 디자인 작업 및 누락 화면 추가
  daily-nuts-client/src/App.css
  daily-nuts-client/src/App.jsx
  daily-nuts-client/src/assets/css/BasicHeader.css
  daily-nuts-client/src/assets/css/Default.css
  daily-nuts-client/src/assets/css/ExpertInfo.css
  daily-nuts-client/src/assets/css/Login.css
  daily-nuts-client/src/assets/css/Notification.css
  daily-nuts-client/src/assets/css/PaymentHistory.css
  daily-nuts-client/src/assets/css/PostDetail.css
  daily-nuts-client/src/assets/css/PostWrite.css
  daily-nuts-client/src/assets/css/Sidebar.css
  daily-nuts-client/src/assets/css/Signup.css
  daily-nuts-client/src/assets/css/Subscribe.css
  daily-nuts-client/src/assets/css/SubscribeModal.css
  daily-nuts-client/src/assets/css/feed.css
  daily-nuts-client/src/assets/css/join.css
  daily-nuts-client/src/assets/css/navigationbar.css
  daily-nuts-client/src/assets/css/profile.css
  daily-nuts-client/src/components/BasicHeader.jsx
  daily-nuts-client/src/components/EditProfile.jsx
  daily-nuts-client/src/components/ExpertInfo.jsx
  daily-nuts-client/src/components/MyPageCard.jsx
  daily-nuts-client/src/components/NotificationItem.jsx
  daily-nuts-client/src/components/PaymentHistory.jsx
  daily-nuts-client/src/components/PostDetailItem.jsx
  daily-nuts-client/src/components/PostForm.jsx
  daily-nuts-client/src/components/PostItem.jsx
  daily-nuts-client/src/components/ReplyItem.jsx
  daily-nuts-client/src/components/Sidebar.jsx
  daily-nuts-client/src/components/SubTab.jsx
  daily-nuts-client/src/components/SubscribeItem.jsx
  daily-nuts-client/src/components/SubscriptionModal.jsx
  daily-nuts-client/src/index.css
  daily-nuts-client/src/layers/BlankHeaderLayout.jsx
  daily-nuts-client/src/layers/DefaultLayout.jsx
  daily-nuts-client/src/layers/TabHeaderLayout.jsx
  daily-nuts-client/src/pages/FeedPage.jsx
  daily-nuts-client/src/pages/LoginPage.jsx
  daily-nuts-client/src/pages/NotificationPage.jsx
  daily-nuts-client/src/pages/PostDetailPage.jsx
  daily-nuts-client/src/pages/PostWritePage.jsx
  daily-nuts-client/src/pages/ProfilePage.jsx
  daily-nuts-client/src/pages/SignupPage.jsx
  daily-nuts-client/src/pages/SubscribeListPage.jsx
Labels: design

#41 refactor: Member객체 JwtMember 객체로 변경
  daily-nuts-server/src/main/java/com/dailynuts/subscription/controller/PaymentController.java
Labels: fix

#52 Feat: 게시글 상세페이지 줄바꿈
  daily-nuts-client/src/assets/css/PostDetail.css
Labels: design

#61 feat: 결제하기 버튼 2일 전부터 보이게 수정
  daily-nuts-client/src/components/PaymentHistory.jsx
Labels: feature

#63 fix: 버튼 날짜 변수 분리 수정
  daily-nuts-client/src/components/PaymentHistory.jsx
Labels: fix

#64 fix: 결제내역에서 결제 시 전문가 Id 조회 에러 수정
  daily-nuts-client/src/components/PaymentHistory.jsx
  daily-nuts-server/src/main/java/com/dailynuts/subscription/dto/PaymentResponseDto.java
  daily-nuts-server/src/main/java/com/dailynuts/subscription/service/mapper/PaymentMapper.java
Labels: fix

#68 feat:댓글 프로필 사진 추가
  daily-nuts-client/src/components/CommentItem.jsx
  daily-nuts-client/src/components/ReplyItem.jsx
  daily-nuts-client/src/pages/PostDetailPage.jsx
  daily-nuts-server/src/main/java/com/dailynuts/post/dto/CommentResponseDto.java
  daily-nuts-server/src/main/java/com/dailynuts/post/service/CommentServiceImpl.java
Labels: feature
